Repository boostcampwm-2021/web30-boostock, pull requests merged in 2021-11, with the labels that each got.

#27 프론트엔드 디렉토리 eslint 설정 수정 및 husky, lint-staged 설정 제거
  front/.eslintrc.json
  front/package-lock.json
  front/package.json
  front/src/_.d.ts
Labels: frontend, fix, chore

#29 typeORM 설정 변경 및 User 처리 코드 추가
  back/src/api/index.ts
  back/src/api/user/index.ts
  back/src/api/user/user.ts
  back/src/interfaces/IUser.ts
  back/src/loaders/express.ts
  back/src/loaders/typeorm.ts
  back/src/models/User.ts
  back/src/models/repository/UserRepository.ts
  back/src/repositories/UserRepository.ts
  back/src/repositories/index.ts
  back/src/services/UserService.ts
  back/src/services/user.ts
Labels: backend, fix

#56 주문 요청 url 수정
  front/src/pages/trade/bidAsk/BidAsk.tsx
Labels: fix

#61 사이드바 다크모드 현재가 컬러 수정
  front/src/app.scss
  front/src/pages/trade/sideBar/sideBarItem/SideBarItem.scss
Labels: fix

#84 다크 모드 변경 시 소켓 재연결 되는 현상 수정
  front/src/Theme.tsx
  front/src/app.scss
  front/src/app.tsx
Labels: fix

#85 체결 로직의 잘못 설정된 값 수정
  auctioneer/src/services/AuctioneerService.ts
  auctioneer/src/services/BidAskTransaction.ts
Labels: backend, fix

#90 사이드바 및 사이드바 아이템 패딩 및 크기 조정
  front/src/pages/trade/sideBar/SideBar.scss
  front/src/pages/trade/sideBar/sideBarItem/SideBarItem.scss
Labels: fix

#91 변수 타입 검증 클래스 추가
  back/src/api/order/order.ts
  back/src/api/user/user.ts
  back/src/helper/Validator.ts
  back/src/helper/index.ts
  back/src/helper/tools.ts
  back/src/repositories/StockRepository.ts
  back/src/services/StockService.ts
  back/src/services/UserService.ts
Labels: backend, feature

#92 주문 취소 및 정정 기능 추가
  auctioneer/src/models/Order.ts
  auctioneer/src/models/Stock.ts
  back/src/models/Order.ts
  back/src/models/Stock.ts
  back/src/repositories/OrderRepository.ts
  back/src/services/OrderService.ts
  back/src/services/errors/OrderError.ts
Labels: backend, feature

#105 로그인 및 회원가입 페이지 추가
  front/assets/icon-github.png
  front/src/app.tsx
  front/src/common/topbar/menu/Menu.tsx
  front/src/pages/signIn/SignIn.scss
  front/src/pages/signIn/SignIn.tsx
  front/src/pages/signUp/SignUp.scss
  front/src/pages/signUp/SignUp.tsx
Labels: frontend

#114 체결 내역 렌더링, 에러 핸들러 수정
  auctioneer/src/services/BidAskTransaction.ts
  back/src/api/middleware/orderValidator.ts
  back/src/api/order/order.ts
  back/src/api/stock/stock.ts
  back/src/helper/AsyncHelper.ts
  back/src/helper/Validator.ts
  back/src/helper/tools.ts
  back/src/loaders/express.ts
  back/src/loaders/mongoose.ts
  back/src/loaders/socket.ts
  back/src/models/Stock.ts
  back/src/models/Transaction.ts
  back/src/services/StockService.ts
  back/src/services/errors/NotFoundError.ts
  back/src/services/errors/StockError.ts
  back/src/services/errors/ValidationError.ts
  back/src/services/errors/index.ts
  front/src/Socket.tsx
  front/src/common/utils/socketUtils.ts
  front/src/pages/trade/bidAsk/BidAsk.tsx
  front/src/pages/trade/conclusion/Conclusion.tsx
  front/src/recoil/stockExecution/atom.ts
Labels: frontend, backend

#127 ManyToOne 어노테이션으로 인한 거래체결 비정상 동작 문제 수정
  auctioneer/src/models/User.ts
  auctioneer/src/models/UserFavorite.ts
  auctioneer/src/models/UserStock.ts
  auctioneer/src/repositories/UserRepository.ts
  auctioneer/src/services/AuctioneerService.ts
  front/src/common/utils/formatInteger.ts
  front/src/pages/my/Holds.tsx
  front/src/pages/my/Info.tsx
Labels: frontend, backend, fix

#134 Auctioneer 서버 및 Backend 서버의 오류 수정
  auctioneer/src/services/BidAskTransaction.ts
  back/src/api/order/order.ts
  back/src/api/user/balance.ts
  back/src/services/OrderService.ts
  front/src/pages/balance/Balance.tsx
  front/src/pages/balance/Deposit.tsx
  front/src/pages/balance/Withdrawal.tsx
  front/src/pages/trade/bidAsk/BidAskInputs.tsx
Labels: backend, fix

#137 타입 오류 수정
  auctioneer/src/services/AuctioneerService.ts
  back/src/api/user/balance.ts
  back/src/api/user/transaction.ts
  back/src/services/UserService.ts
  front/src/global.ts
  front/src/pages/balance/Balance.tsx
  front/src/pages/my/Info.tsx
  front/src/pages/my/Orders.tsx
  front/src/pages/my/Transactions.tsx
Labels: fix

#140 호가 정보창 스타일 수정
  front/src/pages/trade/Trade.scss
  front/src/pages/trade/bidAsk/bidask.scss
  front/src/pages/trade/order/Order.tsx
Labels: fix

#143 주문 체결 로직 수정
  auctioneer/src/models/Chart.ts
  auctioneer/src/services/AuctioneerService.ts
  auctioneer/src/services/BidAskTransaction.ts
  front/src/Socket.tsx
  front/src/recoil/stockList/atom.ts
Labels: fix

#145 체결을 위한 알람 기능 구현
  auctioneer/src/services/BidAskTransaction.ts
  back/src/api/auth/github.ts
  back/src/api/middleware/orderValidator.ts
  back/src/api/order/order.ts
  back/src/api/stock/stock.ts
  back/src/api/user/balance.ts
  back/src/api/user/favorite.ts
  back/src/api/user/hold.ts
  back/src/api/user/transaction.ts
  back/src/api/user/user.ts
  back/src/errors/AuthError.ts
  back/src/errors/CommonError.ts
  back/src/errors/NotFoundError.ts
  back/src/errors/OrderError.ts
  back/src/errors/ParamError.ts
  back/src/errors/StockError.ts
  back/src/errors/UserError.ts
  back/src/errors/ValidationError.ts
  back/src/errors/index.ts
  back/src/helper/Validator.ts
  back/src/helper/tools.ts
  back/src/interfaces/socketRequest.ts
  back/src/loaders/express.ts
  back/src/loaders/socket.ts
  back/src/repositories/UserStockRepository.ts
  back/src/services/GithubService.ts
  back/src/services/OrderService.ts
  back/src/services/StockService.ts
  back/src/services/UserFavoriteService.ts
  back/src/services/UserService.ts
  back/src/services/UserStockService.ts
  back/tsconfig.json
  front/package-lock.json
  front/package.json
  front/src/Socket.tsx
  front/src/app.tsx
  front/src/common/utils/cookie.ts
  front/src/common/utils/eventEmitter.ts
  front/src/common/utils/socketUtils.ts
  front/src/pages/signIn/SignIn.tsx
  front/src/pages/signUp/SignUp.tsx
  front/src/pages/trade/sideBar/SideBar.tsx
  front/src/pages/trade/sideBar/refreshStockData.ts
  front/src/recoil/holdStockList/atom.ts
  front/src/recoil/holdStockList/index.ts
Labels: frontend, backend

#172 Auctioneer 개선 사항 반영
  auctioneer/src/api/message/message.ts
  auctioneer/src/helper/eventEmitter.ts
  auctioneer/src/loaders/index.ts
  auctioneer/src/loaders/matchLogger.ts
  auctioneer/src/models/Order.ts
  auctioneer/src/models/UserStock.ts
  auctioneer/src/repositories/ChartRepository.ts
  auctioneer/src/repositories/OrderRepository.ts
  auctioneer/src/repositories/StockRepository.ts
  auctioneer/src/repositories/UserStockRepository.ts
  auctioneer/src/services/AuctioneerService.ts
  auctioneer/src/services/BidAskTransaction.ts
  back/src/api/stock/stock.ts
  back/src/api/user/order.ts
  back/src/loaders/express.ts
  back/src/repositories/OrderRepository.ts
  back/src/repositories/StockRepository.ts
  back/src/services/StockService.ts
  front/src/Socket.tsx
  front/src/app.tsx
  front/src/pages/trade/Trade.scss
  front/src/pages/trade/conclusion/Conclusion.tsx
  front/src/pages/trade/conclusion/Days.tsx
  front/src/pages/trade/conclusion/Ticks.tsx
Labels: backend

#178 차트 컴포넌트 개선
  front/src/pages/trade/chart/CandleBackground.tsx
  front/src/pages/trade/chart/CandleGraph.tsx
  front/src/pages/trade/chart/CandleLegend.tsx
  front/src/pages/trade/chart/Chart.tsx
  front/src/pages/trade/chart/PeriodBackground.tsx
  front/src/pages/trade/chart/VolumeBackground.tsx
  front/src/pages/trade/chart/VolumeGraph.tsx
  front/src/pages/trade/chart/common.ts
  front/src/pages/trade/chart/useChartData.ts
Labels: frontend, feature

#179 스케줄러로 생성된 차트 데이터 전송
  auctioneer/src/repositories/OrderRepository.ts
  auctioneer/src/services/ScheduleService.ts
  back/src/api/stock/log.ts
  back/src/api/stock/stock.ts
  back/src/loaders/socket.ts
  back/src/services/StockService.ts
  front/src/Socket.tsx
  front/src/pages/trade/Trade.tsx
  front/src/pages/trade/chart/Chart.tsx
  front/src/pages/trade/conclusion/Conclusion.tsx
  front/src/pages/trade/conclusion/Days.tsx
Labels: backend

#186 일별 종목 정보 렌더링, 로그아웃 로직 추가 구현
  back/src/api/auth/signout.ts
  back/src/api/stock/stock.ts
  back/src/loaders/socket.ts
  back/src/services/StockService.ts
  front/src/Socket.tsx
  front/src/pages/trade/conclusion/Conclusion.tsx
  front/src/pages/trade/conclusion/Days.tsx
  front/src/pages/trade/conclusion/conclusion.scss
  front/src/recoil/stockDailyLog/atom.ts
  front/src/recoil/stockDailyLog/index.ts
Labels: frontend, backend

#191 입출금 페이지 다크모드 버그 수정 및 기타 스타일 수정
  front/src/pages/balance/Balance.scss
  front/src/pages/balance/Balance.tsx
  front/src/pages/my/Holds.scss
  front/src/pages/my/Holds.tsx
  front/src/pages/my/My.scss
  front/src/pages/my/Orders.scss
  front/src/pages/my/Orders.tsx
  front/src/pages/my/Transactions.scss
  front/src/pages/my/Transactions.tsx
Labels: fix, style

#197 [CI] 환경변수(secrets)를 백엔드 환경변수에서 별도로 분리
  .github/workflows/testBackend.yml
Labels: chore

#199 로그인 실패 시, 토스트 메시지가 무한히 발생하는 오류 수정
  front/src/pages/signIn/SignIn.tsx
  front/src/pages/signUp/SignUp.tsx
Labels: frontend, fix

#200 차트 컴포넌트 위주 리팩토링
  front/.eslintrc.json
  front/src/pages/main/Main.tsx
  front/src/pages/trade/Trade.tsx
  front/src/pages/trade/chart/CandleBackground.tsx
  front/src/pages/trade/chart/CandleLegend.tsx
  front/src/pages/trade/chart/Chart.tsx
  front/src/pages/trade/chart/PeriodBackground.tsx
  front/src/pages/trade/chart/PeriodLegend.tsx
  front/src/pages/trade/chart/VolumeBackground.tsx
  front/src/pages/trade/chart/VolumeGraph.tsx
  front/src/pages/trade/chart/VolumeLegend.tsx
  front/src/pages/trade/chart/candle/CandleBackground.tsx
  front/src/pages/trade/chart/candle/CandleGraph.tsx
  front/src/pages/trade/chart/candle/CandleLegend.tsx
  front/src/pages/trade/chart/common.ts
  front/src/pages/trade/chart/fetchChartData.ts
  front/src/pages/trade/chart/hooks/useChart.tsx
  front/src/pages/trade/chart/period/PeriodBackground.tsx
  front/src/pages/trade/chart/period/PeriodLegend.tsx
  front/src/pages/trade/chart/useChartData.ts
  front/src/pages/trade/chart/volume/VolumeBackground.tsx
  front/src/pages/trade/chart/volume/VolumeGraph.tsx
  front/src/pages/trade/chart/volume/VolumeLegend.tsx
Labels: refactor

#201 체결 컴포넌트에 유저가 확인 중인 종목의 체결 내역만 조건 추가, backend의 validator 미들웨어
  back/src/api/auth/github.ts
  back/src/api/auth/signout.ts
  back/src/api/middleware/logValidator.ts
  back/src/api/middleware/orderValidator.ts
  back/src/api/middleware/sessionValidator.ts
  back/src/api/stock/log.ts
  back/src/api/user/balance.ts
  back/src/api/user/favorite.ts
  back/src/api/user/hold.ts
  back/src/api/user/order.ts
  back/src/api/user/transaction.ts
  back/src/api/user/user.ts
  back/src/loaders/socket.ts
  back/src/services/StockService.ts
  front/src/Socket.tsx
  front/src/pages/trade/conclusion/Conclusion.tsx
  front/src/pages/trade/conclusion/Ticks.tsx
  front/src/recoil/stockExecution/atom.ts
Labels: frontend, backend

#202 hotfix:log validator 미들웨어 적용, 차트 날짜표기 오류 수정
  back/src/api/middleware/logValidator.ts
  back/src/api/stock/log.ts
  front/src/pages/trade/chart/period/PeriodLegend.tsx
Labels: frontend, backend

#203 1일봉 차트에서 날짜를 월/일로 표시합니다
  front/src/pages/trade/chart/Chart.tsx
  front/src/pages/trade/chart/common.ts
  front/src/pages/trade/chart/period/PeriodBackground.tsx
Labels: frontend

#204 fix: 차트 날짜 표기 오류 수정
  front/src/pages/trade/chart/period/PeriodLegend.tsx
Labels: fix
