Repository boostcampwm-2021/web30-boostock, pull requests merged in 2021-12, with the labels that each got.

#208 1분/1일봉 로그 데이터 저장 로직 핫픽스
  auctioneer/src/services/ScheduleService.ts
Labels: fix

#205 feat: 주문 체결 시 주문 가능 수량 업데이트 로직 수정
  front/src/Socket.tsx
  front/src/common/utils/fetchHoldStocks.ts
  front/src/common/utils/getAvailableAmount.ts
  front/src/pages/trade/bidAsk/BidAsk.tsx
Labels: feature

#209 [리팩토링] 소켓 로직 분리 및 이벤트 재정의
  auctioneer/src/api/message/message.ts
  auctioneer/src/loaders/matchLogger.ts
  back/package-lock.json
  back/package.json
  back/src/api/auth/github.ts
  back/src/api/auth/signout.ts
  back/src/api/middleware/logValidator.ts
  back/src/api/middleware/orderValidator.ts
  back/src/api/stock/log.ts
  back/src/api/stock/stock.ts
  back/src/api/user/balance.ts
  back/src/api/user/hold.ts
  back/src/api/user/order.ts
  back/src/loaders/index.ts
  back/src/loaders/socket.ts
  back/src/services/SocketService.ts
  front/src/Socket.tsx
  front/src/app.tsx
  front/src/pages/signIn/SignIn.tsx
  front/src/pages/signUp/SignUp.tsx
  front/src/pages/trade/bidAsk/BidAsk.tsx
Labels: frontend, backend, refactor

#210 [리팩토링] 체결내역, 주문내역에 인피니티 스크롤 적용
  back/src/api/user/order.ts
  back/src/services/UserService.ts
  front/src/pages/my/Orders.tsx
  front/src/pages/my/Transactions.tsx
  front/src/pages/my/useInfinityScroll.ts
Labels: refactor

#212 회원가입 약관 추가
  auctioneer/src/api/index.ts
  auctioneer/src/loaders/chartLogger.ts
  auctioneer/src/repositories/OrderRepository.ts
  auctioneer/src/services/AuctioneerService.ts
  auctioneer/src/services/BidAskTransaction.ts
  back/src/api/stock/bid-ask.ts
  back/src/api/stock/stock.ts
  back/src/api/user/balance.ts
  back/src/api/user/favorite.ts
  back/src/api/user/hold.ts
  back/src/api/user/user.ts
  back/src/errors/UserError.ts
  back/src/helper/index.ts
  back/src/repositories/StockRepository.ts
  back/src/repositories/UserRepository.ts
  back/src/services/GithubService.ts
  back/src/services/OrderService.ts
  back/src/services/StockService.ts
  back/src/services/UserFavoriteService.ts
  back/src/services/UserService.ts
  front/src/pages/signUp/SignUp.scss
  front/src/pages/signUp/SignUp.tsx
  front/src/pages/signUp/Terms.tsx
Labels: frontend, backend

#213 종목 정보가 변동될때마다 보유종목이 재차 갱신되던 부분을 개선
  front/src/pages/my/My.tsx
Labels: frontend

#215 fix:트레이딩 봇을 위한 주문 API 수정
  back/src/api/user/order.ts
Labels: backend

#216 feat: 미체결 주문 확인 API 수정
  auctioneer/src/services/AuctioneerService.ts
  back/src/api/auth/signout.ts
  back/src/api/user/order.ts
  back/src/interfaces/IOrder.ts
  back/src/repositories/AskOrderRepository.ts
  back/src/repositories/UserStockRepository.ts
  back/src/services/CancleTransaction.ts
  back/src/services/OrderService.ts
  back/src/services/OrderTransaction.ts
  back/src/services/UserService.ts
Labels: refactor

#217 타입, 아톰 리팩토링
  front/src/Socket.tsx
  front/src/Theme.tsx
  front/src/app.tsx
  front/src/common/topbar/menu/Menu.tsx
  front/src/common/utils/getAvailableAmount.ts
  front/src/global.ts
  front/src/pages/balance/Balance.tsx
  front/src/pages/my/Holds.tsx
  front/src/pages/my/Info.tsx
  front/src/pages/my/My.tsx
  front/src/pages/my/Orders.tsx
  front/src/pages/my/Transactions.tsx
  front/src/pages/my/api/fetchUserHold.ts
  front/src/pages/signIn/SignIn.tsx
  front/src/pages/signUp/SignUp.tsx
  front/src/pages/trade/Trade.tsx
  front/src/pages/trade/bidAsk/BidAsk.tsx
  front/src/pages/trade/bidAsk/BidAskAction.tsx
  front/src/pages/trade/chart/Chart.tsx
  front/src/pages/trade/chart/candle/CandleBackground.tsx
  front/src/pages/trade/chart/candle/CandleGraph.tsx
  front/src/pages/trade/chart/candle/CandleLegend.tsx
  front/src/pages/trade/chart/common.ts
  front/src/pages/trade/chart/fetchChartData.ts
  front/src/pages/trade/chart/hooks/useChart.tsx
  front/src/pages/trade/chart/period/PeriodBackground.tsx
  front/src/pages/trade/chart/period/PeriodLegend.tsx
  front/src/pages/trade/chart/volume/VolumeBackground.tsx
  front/src/pages/trade/chart/volume/VolumeGraph.tsx
  front/src/pages/trade/chart/volume/VolumeLegend.tsx
  front/src/pages/trade/conclusion/Days.tsx
  front/src/pages/trade/conclusion/Ticks.tsx
  front/src/pages/trade/order/AskOrderItem.tsx
  front/src/pages/trade/order/BidOrderItem.tsx
  front/src/pages/trade/order/Order.tsx
  front/src/pages/trade/sideBar/SideBar.tsx
  front/src/pages/trade/sideBar/sideBarItem/SideBarItem.tsx
  front/src/pages/trade/stockInfo/StockInfo.tsx
  front/src/recoil/bidAskPrice/index.ts
  front/src/recoil/chart/atom.ts
  front/src/recoil/chart/index.ts
  front/src/recoil/holdStockList/index.ts
  front/src/recoil/stockDailyLog/atom.ts
  front/src/recoil/stockDailyLog/index.ts
  front/src/recoil/stockExecution/atom.ts
  front/src/recoil/stockExecution/index.ts
  front/src/recoil/stockList/atom.ts
  front/src/recoil/stockList/index.ts
  front/src/recoil/stockOrders/atom.ts
  front/src/recoil/stockOrders/index.ts
  front/src/recoil/user/atom.ts
  front/src/recoil/user/index.ts
  front/src/recoil/websocket/index.ts
  front/src/types.ts
Labels: refactor

#218 주문 테이블 분리에 따라 매도내역 매수내역 페이지를 분리
  front/src/pages/my/My.tsx
  front/src/pages/my/Orders.tsx
Labels: frontend

#221 fix: 거래량이 0인 그래프는 그리지 않도록 수정
  front/src/pages/trade/chart/volume/VolumeGraph.tsx
Labels: fix

#222 feat: 쿠키 httpOnly, secure, sameSite 옵션 설정
  back/src/loaders/session.ts
Labels: feature

#223 Hotfix: useChart 수정, useToasterStore 제거 등
  front/src/app.tsx
  front/src/common/topbar/TopBar.tsx
  front/src/common/topbar/menu/Menu.tsx
  front/src/pages/balance/Deposit.tsx
  front/src/pages/balance/Withdrawal.tsx
  front/src/pages/trade/chart/hooks/useChart.tsx
Labels: fix

#225 docs: README 수정
  README.md
  back/src/config/index.ts
  back/src/loaders/session.ts
  back/src/services/UserService.ts
  docs/erd.png
Labels: docs
